## 字典法的缺點

如果以前沒看過這個字  
就沒輒了

## 讓我們先建立一個語意模型吧 - word2vec

![img](https://www.extremetech.com/wp-content/uploads/2015/10/AI-640x353.jpg)



將所有的單字透過One hot encoding編碼  
送進類神經網路訓練  

![img](http://lh3.googleusercontent.com/-Ku4A62Vw5dQ/V4RaKeQaDOI/AAAAAAAACoA/NWmlYfi4-RIuD43knrC2bYCXJmKtQIjTACCo/s565/pic_1.png)

接下來教大家如何建立一個word2vec的模型  
[github連結](https://github.com/udicatnchu/kem)
# KEM

訓練Word2Vec model參考文章：[以 gensim 訓練中文詞向量](http://zake7749.github.io/2016/08/28/word2vec-with-gensim/)

## Get Started

## Installing

1. `pip install kem`

## Run
#### Building the model  
使用api前必須先建立model  
停用詞以及結巴斷詞的字典在這邊  

> 1. 結巴字典：格式是txt, 在 [Open-Sentiment-Training-Data](https://github.com/UDICatNCHU/Open-Sentiment-Training-Data)當中，有數份字典
可以依需求將字典合併成一份後再去斷詞，效果會不同。  
> 2. 停用詞：有在停用詞裏面的單字會被當作冗詞贅字給濾掉，在此應用中只需要拿 [stopwrds](https://github.com/UDICatNCHU/Open-Sentiment-Training-Data/tree/master/stopwrds)裏面的stopwrds.json即可

1. `python manage.py buildkem 結巴自訂字典path 停用詞path 欲訓練model之維度(目前是400維，維度愈大檔案愈大)`

#### Usage of KEM class  
因為KEM是一個django的函式庫，所以需要設定urls.py以及vies.py  
並且在settings.py INSTALLED_APPS 新增kem喔

1. settings.py：
  ```
  INSTALLED_APPS = [
      'kem'
       ...
  ]
  ```
2. urls.py：  
在專案的urls.py引入函式庫的urls.py即可使用該api  
  ```
  import kem.urls
  urlpatterns += [
      url(r'^kem/', include(kem.urls))
  ]
  ```


## API
1. 取得字的向量：_`/kem`_
  - keyword
  - num
  - example：[http://140.120.13.244:10000/kem?keyword=草履蟲&num=100](http://140.120.13.244:10000/kem?keyword=草履蟲&num=100)

  ```
  ['原生動物', 0.7895185351371765]
  ['藍菌', 0.7865398526191711]
  ['甲藻', 0.7792112827301025]
  ['藍綠藻', 0.7636655569076538]
  ['芽孢', 0.7631546258926392]
  ['兼性', 0.7622398138046265]
  ['纖毛蟲', 0.7605307102203369]
  ['專性', 0.7589520215988159]
  ['莢膜', 0.7575902938842773]
  ['蟲類', 0.7529693841934204]
  ['菌門', 0.7505052089691162]
  ['厚壁', 0.75014328956604]
  ['厭氧菌', 0.7490075826644897]
  ['桿菌屬', 0.7489725947380066]
  ['變形蟲', 0.748399555683136]
  ['介殼', 0.7460906505584717]
  ['節肢動物', 0.7445138692855835]
  ['纖毛', 0.744355320930481]
  ['革蘭氏', 0.7432918548583984]
  ['黴菌', 0.7408658266067505]
  ...
  etc
  ```### 先學一下numpy吧

這是一個用C語言去實作的函式庫  
讓陣列的記憶體變成連續（python的陣列是用一張記憶體的Table去查詢，速度慢且記憶體位置不連續）  
大部份deep learning函式庫都以numpy的nd array為input data的格式

* ndarray.ndim
    * 回傳這個ndarray的dimension是多少
* ndarray.shape
    * 用一個tuple表示他是幾乘幾的矩陣
* ndarray.size
    * 矩陣總共有多少item
* ndarray.dtype
    * 顯示資料型態。numpy陣列裏面每個元件都要有一樣的資料型態，numpy.int32, numpy.int16, and numpy.float64 are some examples.
* ndarray.itemsize
    * 顯示每個element佔了幾個bytes


### 先學一下numpy吧

這是一個用C語言去實作的函式庫  
讓陣列的記憶體變成連續（python的陣列是用一張記憶體的Table去查詢，速度慢且記憶體位置不連續）  
大部份deep learning函式庫都以numpy的nd array為input data的格式

* ndarray.ndim
    * 回傳這個ndarray的dimension是多少
* ndarray.shape
    * 用一個tuple表示他是幾乘幾的矩陣
* ndarray.size
    * 矩陣總共有多少item
* ndarray.dtype
    * 顯示資料型態。numpy陣列裏面每個元件都要有一樣的資料型態，numpy.int32, numpy.int16, and numpy.float64 are some examples.
* ndarray.itemsize
    * 顯示每個element佔了幾個bytes


In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))
b = np.array([6, 7, 8])
print(type(b))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Array Creation

In [3]:
print(np.array([2,3,4]))
print(np.array([1.2, 3.5, 5.1]))
print(np.array([(1.5,2,3), (4,5,6)]))
print(np.zeros( (3,4) ))

[2 3 4]
[ 1.2  3.5  5.1]
[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


### 類似python內建的range函式
支援小數點  
也能指定a~b範圍內切成幾等份

In [5]:
print(np.arange( 10, 30, 5 ))
print(np.arange( 0, 2, 0.3 ))
print(np.linspace( 0, 2, 9 ))

[10 15 20 25]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8]
[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


將一維的陣列  
轉換成任意維度的矩陣
```
>>> a = np.arange(6)                         # 1d array
>>> print(a)
[0 1 2 3 4 5]
>>>
>>> b = np.arange(12).reshape(4,3)           # 2d array
>>> print(b)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
>>>
>>> c = np.arange(24).reshape(2,3,4)         # 3d array
>>> print(c)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]
 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
```

### 基本的矩陣操作 加減乘除
```
>>> a = np.array( [20,30,40,50] )
>>> b = np.arange( 4 )
>>> b
array([0, 1, 2, 3])
>>> c = a-b
>>> c
array([20, 29, 38, 47])
>>> b**2
array([0, 1, 4, 9])
>>> a<35
array([ True, True, False, False], dtype=bool)
>>> A = np.array( [[1,1],
...             [0,1]] )
>>> B = np.array( [[2,0],
...             [3,4]] )
>>> A*B                         # elementwise product
array([[2, 0],
       [0, 4]])
>>> A.dot(B)                    # matrix product
array([[5, 4],
       [3, 4]])
>>> np.dot(A, B)                # another matrix product
array([[5, 4],
       [3, 4]])
```

### 將句子透過word2vec轉換成向量

這步驟因為需要很多時間  
所以我們已經預處理好  
回去時，大家只要透過gensim的API，即可將句子轉換成向量  
```
from gensim import models
model = models.KeyedVectors.load_word2vec_format('med400.model.bin', binary=True)

model[單字] # 這樣就能得到該單字的向量
```

### 透過spark將向量檔轉換成numpy格式

<mark style='color:red'>（此block可選擇性閱讀）  </mark>  
（因為spark環境不便再課堂上讓所有人操作，所以已經預先將此block的程式執行結果準備好給大家了）  
下列程式碼請在spark環境下執行


In [ ]:
import pyspark
conf = pyspark.SparkConf().setAll([('spark.driver.memory', '30g'), ('spark.driver.host', '172.17.0.21'), ('spark.app.id', 'local-1492693477461'), ('spark.rdd.compress', 'True'), ('spark.serializer.objectStreamReset', '100'), ('spark.master', 'local[*]'), ('spark.executor.id', 'driver'), ('spark.submit.deployMode', 'client'), ('spark.driver.port', '39274'), ('spark.app.name', 'PySparkShell')])
spark = pyspark.SparkContext(conf=conf)
neg_df = spark.read  .format('org.apache.spark.sql.execution.datasources.csv.CSVFileFormat')  .option('header', 'true')  .load('neg.csv')
pos_df = spark.read  .format('org.apache.spark.sql.execution.datasources.csv.CSVFileFormat')  .option('header', 'true')  .load('pos.csv')
training_df = neg_df.union(pos_df)

def featureExtraction(x):
    vector = []
    if x[0]==u'p':
        vector.append(1)
    else:
        vector.append(0)
    for i in range(1,401):
        vector.append(float(x[i]))
    return vector

train = training_df.rdd.map(featureExtraction).cache()

import numpy as np

train = np.array(train.collect())
train.dump('trainData.numpy')

## 第一次學類神經網路就上手 -> Keras

> pip install keras tensorflow

`train_test_split(data[:, 1:], data[:, 0], test_size=0.99, random_state=42)`  
意思是說把訓練資料切出99%當作測試資料 1%當作訓練資料  
會這樣設計的原因是因為  
類神經網路的訓練其實是非常花時間的  
上課期間恐怕沒辦法讓各位跑出結果  
所以我們調整訓練資料的大小（2000筆）  
但是資料太少導致訓練的準確度幾乎是100%正確  
現實生活中不太可能發生這種事情  
為了避免出現100%，所以將難度提高（只給機器學習1%資料，99%拿去考他）  
最後得到 `0.998989898749` 的準確度



In [ ]:
import numpy as np

# 載入我們預處理好的向量
# 將其轉換成numpy型態

data = np.load('miniTrainData.numpy')
from sklearn.cross_validation import train_test_split
data_train, data_test, labels_train, labels_test = train_test_split(data[:, 1:], data[:, 0], test_size=0.99, random_state=42)

from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout

batch_size = 20

model = Sequential()
model.add(Dense(input_dim=400, units=200, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.summary()

In [ ]:
# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('Train...')
model.fit(data_train, labels_train,
          batch_size=batch_size,
          epochs=5,
          validation_data=(data_test, labels_test))
score, acc = model.evaluate(data_test, labels_test,
                            batch_size=batch_size)
print('Test score:', score)
print('Test accuracy:', acc)